import { useState, useRef, useEffect, useCallback } from 'react'

// ── Constants ─────────────────────────────────────────────────────────────────
const EASINGS = {
  'linear':      'linear',
  'ease':        'ease',
  'ease-in':     'ease-in',
  'ease-out':    'ease-out',
  'ease-in-out': 'ease-in-out',
  'bounce':      'cubic-bezier(0.34, 1.56, 0.64, 1)',
  'spring':      'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
  'snap':        'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
  'slow-in':     'cubic-bezier(0.42, 0, 1, 1)',
  'slow-out':    'cubic-bezier(0, 0, 0.58, 1)',
}

const SHAPES = ['circle', 'square', 'rounded', 'triangle', 'ring']
const ELEMENT_COLORS = ['#D4AF37', '#FF6B35', '#4ECDC4', '#A78BFA', '#F9CA24', '#FF8B94', '#88D8B0']

const DEFAULT_PROPS = {
  x: 0, y: 0,
  rotate: 0,
  scaleX: 1, scaleY: 1,
  opacity: 1,
  color: '#D4AF37',
}

function makeElement(id, index) {
  return {
    id,
    name: `element ${index + 1}`,
    shape: SHAPES[index % SHAPES.length],
    color: ELEMENT_COLORS[index % ELEMENT_COLORS.length],
    size: 60,
    keyframes: [
      { time: 0,   props: { ...DEFAULT_PROPS } },
      { time: 100, props: { ...DEFAULT_PROPS } },
    ],
  }
}

// ── Interpolation ─────────────────────────────────────────────────────────────
function lerp(a, b, t) { return a + (b - a) * t }

function getPropsAtTime(keyframes, t) {
  if (keyframes.length === 0) return { ...DEFAULT_PROPS }
  if (t <= keyframes[0].time) return { ...keyframes[0].props }
  if (t >= keyframes[keyframes.length - 1].time) return { ...keyframes[keyframes.length - 1].props }

  let prev = keyframes[0], next = keyframes[1]
  for (let i = 0; i < keyframes.length - 1; i++) {
    if (t >= keyframes[i].time && t <= keyframes[i + 1].time) {
      prev = keyframes[i]; next = keyframes[i + 1]; break
    }
  }
  const span = next.time - prev.time
  const frac = span === 0 ? 0 : (t - prev.time) / span
  const p = prev.props, n = next.props
  return {
    x:       lerp(p.x,       n.x,       frac),
    y:       lerp(p.y,       n.y,       frac),
    rotate:  lerp(p.rotate,  n.rotate,  frac),
    scaleX:  lerp(p.scaleX,  n.scaleX,  frac),
    scaleY:  lerp(p.scaleY,  n.scaleY,  frac),
    opacity: lerp(p.opacity, n.opacity, frac),
    color:   p.color, // snap color at midpoint
  }
}

// ── CSS Export ────────────────────────────────────────────────────────────────
function generateCSS(elements, duration, easing) {
  const easingVal = EASINGS[easing] || easing
  let css = `/* Generated by AnimationStudio — DzifaVerse */\n\n`

  elements.forEach(el => {
    const name = el.name.replace(/\s+/g, '-').toLowerCase()
    css += `.${name} {\n`
    css += `  animation: ${name}-anim ${duration}ms ${easingVal} infinite;\n`
    css += `  width: ${el.size}px;\n`
    css += `  height: ${el.size}px;\n`
    css += `  background: ${el.color};\n`
    if (el.shape === 'circle' || el.shape === 'ring') css += `  border-radius: 50%;\n`
    if (el.shape === 'rounded') css += `  border-radius: 16px;\n`
    if (el.shape === 'ring') { css += `  background: transparent;\n`; css += `  border: 6px solid ${el.color};\n` }
    css += `}\n\n`

    css += `@keyframes ${name}-anim {\n`
    el.keyframes.forEach(kf => {
      const p = kf.props
      css += `  ${kf.time}% {\n`
      css += `    transform: translate(${p.x}px, ${p.y}px) rotate(${p.rotate}deg) scale(${p.scaleX}, ${p.scaleY});\n`
      css += `    opacity: ${p.opacity};\n`
      if (p.color !== el.color) css += `    background: ${p.color};\n`
      css += `  }\n`
    })
    css += `}\n\n`
  })

  return css
}

// ── Small UI ──────────────────────────────────────────────────────────────────
function Label({ children }) {
  return <div style={{ fontFamily: '"Courier New", monospace', fontSize: '0.58rem', fontWeight: 700, letterSpacing: '0.12em', color: 'rgba(212,175,55,0.5)', marginBottom: '0.3rem' }}>{children}</div>
}

function Slider({ label, value, min, max, step = 1, onChange, unit = '' }) {
  return (
    <div style={{ marginBottom: '0.6rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.25rem' }}>
        <Label>{label}</Label>
        <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.68rem', color: '#D4AF37' }}>{typeof value === 'number' ? value.toFixed(step < 1 ? 2 : 0) : value}{unit}</span>
      </div>
      <input type="range" min={min} max={max} step={step} value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        style={{ width: '100%', accentColor: '#D4AF37', cursor: 'pointer', height: '4px' }}
      />
    </div>
  )
}

function PanelSection({ title, children }) {
  const [open, setOpen] = useState(true)
  return (
    <div style={{ marginBottom: '0.4rem', borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
      <button onClick={() => setOpen(!open)} style={{
        width: '100%', padding: '0.6rem 0.8rem', background: 'none', border: 'none',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer',
      }}>
        <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.62rem', fontWeight: 700, letterSpacing: '0.1em', color: 'rgba(255,255,255,0.5)' }}>{title}</span>
        <span style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.7rem' }}>{open ? '▲' : '▼'}</span>
      </button>
      {open && <div style={{ padding: '0 0.8rem 0.8rem' }}>{children}</div>}
    </div>
  )
}

// ── Shape renderer ────────────────────────────────────────────────────────────
function ShapeEl({ el, props, selected, onClick }) {
  const size = el.size
  const base = {
    position: 'absolute',
    width: size, height: size,
    left: '50%', top: '50%',
    marginLeft: -size / 2, marginTop: -size / 2,
    transform: `translate(${props.x}px, ${props.y}px) rotate(${props.rotate}deg) scale(${props.scaleX}, ${props.scaleY})`,
    opacity: props.opacity,
    cursor: 'pointer',
    outline: selected ? `2px solid #D4AF37` : 'none',
    outlineOffset: '3px',
    transition: 'outline 0.1s',
    boxSizing: 'border-box',
  }

  if (el.shape === 'circle') return <div onClick={onClick} style={{ ...base, background: props.color, borderRadius: '50%' }} />
  if (el.shape === 'square') return <div onClick={onClick} style={{ ...base, background: props.color }} />
  if (el.shape === 'rounded') return <div onClick={onClick} style={{ ...base, background: props.color, borderRadius: '16px' }} />
  if (el.shape === 'ring') return <div onClick={onClick} style={{ ...base, border: `6px solid ${props.color}`, borderRadius: '50%', background: 'transparent' }} />
  if (el.shape === 'triangle') {
    return (
      <div onClick={onClick} style={{
        ...base, background: 'transparent',
        width: 0, height: 0,
        borderLeft: `${size / 2}px solid transparent`,
        borderRight: `${size / 2}px solid transparent`,
        borderBottom: `${size}px solid ${props.color}`,
        outline: 'none',
        boxShadow: selected ? `0 0 0 2px #D4AF37` : 'none',
      }} />
    )
  }
  return null
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function AnimationStudio() {
  const [elements,    setElements]    = useState([makeElement('e1', 0)])
  const [selectedId,  setSelectedId]  = useState('e1')
  const [currentTime, setCurrentTime] = useState(0)   // 0–100
  const [isPlaying,   setIsPlaying]   = useState(false)
  const [duration,    setDuration]    = useState(2000) // ms
  const [easing,      setEasing]      = useState('ease-in-out')
  const [showCode,    setShowCode]    = useState(false)
  const [copied,      setCopied]      = useState(false)
  const [draggingKf,  setDraggingKf]  = useState(null) // { elId, kfIndex }
  const [timelineDragging, setTimelineDragging] = useState(false)

  const rafRef       = useRef(null)
  const startRef     = useRef(null)
  const timelineRef  = useRef(null)
  const pauseTimeRef = useRef(0)

  const selected = elements.find(e => e.id === selectedId)

  // ── Playback ──
  useEffect(() => {
    if (!isPlaying) { if (rafRef.current) cancelAnimationFrame(rafRef.current); return }
    startRef.current = performance.now() - (pauseTimeRef.current / 100) * duration

    const tick = (now) => {
      const elapsed = now - startRef.current
      const t = ((elapsed % duration) / duration) * 100
      setCurrentTime(t)
      pauseTimeRef.current = t
      rafRef.current = requestAnimationFrame(tick)
    }
    rafRef.current = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(rafRef.current)
  }, [isPlaying, duration])

  const togglePlay = () => {
    if (!isPlaying) pauseTimeRef.current = currentTime
    setIsPlaying(p => !p)
  }

  const stopPlay = () => {
    setIsPlaying(false)
    setCurrentTime(0)
    pauseTimeRef.current = 0
  }

  // ── Element ops ──
  const addElement = () => {
    const id = `e${Date.now()}`
    const idx = elements.length
    const el = makeElement(id, idx)
    setElements(prev => [...prev, el])
    setSelectedId(id)
  }

  const removeElement = (id) => {
    setElements(prev => prev.filter(e => e.id !== id))
    if (selectedId === id) setSelectedId(elements[0]?.id || null)
  }

  const updateElement = (id, patch) => {
    setElements(prev => prev.map(e => e.id === id ? { ...e, ...patch } : e))
  }

  // ── Keyframe ops ──
  const getKfAtTime = (el, t) => el.keyframes.find(k => Math.abs(k.time - t) < 1)

  const addOrUpdateKf = (elId, time, propsPatch) => {
    setElements(prev => prev.map(el => {
      if (el.id !== elId) return el
      const existing = el.keyframes.find(k => Math.abs(k.time - time) < 1)
      const currentProps = getPropsAtTime(el.keyframes, time)
      if (existing) {
        return { ...el, keyframes: el.keyframes.map(k => Math.abs(k.time - time) < 1 ? { ...k, props: { ...currentProps, ...propsPatch } } : k).sort((a, b) => a.time - b.time) }
      } else {
        return { ...el, keyframes: [...el.keyframes, { time, props: { ...currentProps, ...propsPatch } }].sort((a, b) => a.time - b.time) }
      }
    }))
  }

  const removeKf = (elId, kfIdx) => {
    setElements(prev => prev.map(el => {
      if (el.id !== elId) return el
      if (el.keyframes.length <= 2) return el
      return { ...el, keyframes: el.keyframes.filter((_, i) => i !== kfIdx) }
    }))
  }

  // ── Prop change → auto keyframe ──
  const handlePropChange = (prop, value) => {
    if (!selected) return
    const t = Math.round(currentTime)
    addOrUpdateKf(selected.id, t, { [prop]: value })
  }

  // ── Timeline scrub ──
  const scrubTimeline = useCallback((e) => {
    if (!timelineRef.current) return
    const rect = timelineRef.current.getBoundingClientRect()
    const x = Math.max(0, Math.min(e.clientX - rect.left, rect.width))
    const t = (x / rect.width) * 100
    setCurrentTime(t)
    pauseTimeRef.current = t
    if (isPlaying) { setIsPlaying(false) }
  }, [isPlaying])

  // ── Current props for selected ──
  const currentProps = selected ? getPropsAtTime(selected.keyframes, currentTime) : DEFAULT_PROPS

  // ── CSS output ──
  const cssCode = generateCSS(elements, duration, easing)

  const copyCSS = () => {
    navigator.clipboard.writeText(cssCode)
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  // ── Layout dims ──
  const PANEL_W   = 220
  const TIMELINE_H = 140
  const TOPBAR_H   = 48

  return (
    <div style={{ minHeight: '100vh', background: '#0D0D14', paddingTop: '80px', display: 'flex', flexDirection: 'column' }}>

      {/* ── Page header ── */}
      <div style={{ padding: '1.5rem 1.5rem 0.8rem', borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.3rem' }}>
          <div style={{ width: '24px', height: '2px', background: '#D4AF37' }} />
          <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.15em', color: '#D4AF37' }}>the lab</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.8rem' }}>
          <h1 style={{ fontFamily: 'Georgia, serif', fontSize: 'clamp(1.5rem, 4vw, 2.2rem)', fontWeight: 700, color: '#F0EDE8', margin: 0, letterSpacing: '-0.02em' }}>
            Animation Studio 🎞
          </h1>
          <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', flexWrap: 'wrap' }}>
            {/* Duration */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.6rem', color: 'rgba(255,255,255,0.35)', letterSpacing: '0.08em' }}>DURATION</span>
              <select value={duration} onChange={e => setDuration(Number(e.target.value))}
                style={{ background: 'rgba(255,255,255,0.07)', border: '2px solid rgba(255,255,255,0.1)', borderRadius: '6px', color: '#F0EDE8', fontFamily: '"Courier New", monospace', fontSize: '0.75rem', padding: '0.3rem 0.5rem', cursor: 'pointer', outline: 'none' }}>
                {[500, 1000, 1500, 2000, 3000, 4000, 5000].map(d => <option key={d} value={d} style={{ background: '#1A1A2E' }}>{d}ms</option>)}
              </select>
            </div>
            {/* Easing */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.6rem', color: 'rgba(255,255,255,0.35)', letterSpacing: '0.08em' }}>EASING</span>
              <select value={easing} onChange={e => setEasing(e.target.value)}
                style={{ background: 'rgba(255,255,255,0.07)', border: '2px solid rgba(255,255,255,0.1)', borderRadius: '6px', color: '#F0EDE8', fontFamily: '"Courier New", monospace', fontSize: '0.75rem', padding: '0.3rem 0.5rem', cursor: 'pointer', outline: 'none' }}>
                {Object.keys(EASINGS).map(k => <option key={k} value={k} style={{ background: '#1A1A2E' }}>{k}</option>)}
              </select>
            </div>
            {/* Play controls */}
            <div style={{ display: 'flex', gap: '0.35rem' }}>
              <button onClick={togglePlay} style={{ padding: '0.4rem 0.9rem', background: isPlaying ? 'rgba(212,175,55,0.2)' : '#D4AF37', border: `2px solid #D4AF37`, borderRadius: '7px', color: isPlaying ? '#D4AF37' : '#0D0D14', fontFamily: 'Georgia, serif', fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer', transition: 'all 0.13s' }}>
                {isPlaying ? '⏸ pause' : '▶ play'}
              </button>
              <button onClick={stopPlay} style={{ padding: '0.4rem 0.7rem', background: 'transparent', border: '2px solid rgba(255,255,255,0.15)', borderRadius: '7px', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '0.8rem' }}>■</button>
            </div>
            {/* Export */}
            <button onClick={() => setShowCode(s => !s)} style={{ padding: '0.4rem 0.9rem', background: showCode ? 'rgba(78,205,196,0.2)' : 'transparent', border: '2px solid rgba(78,205,196,0.4)', borderRadius: '7px', color: '#4ECDC4', fontFamily: 'Georgia, serif', fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer', transition: 'all 0.13s' }}>
              {'</>'} export CSS
            </button>
          </div>
        </div>
      </div>

      {/* ── Main editor area ── */}
      <div style={{ flex: 1, display: 'flex', overflow: 'hidden', minHeight: 0 }}>

        {/* ── Left: Elements panel ── */}
        <div style={{ width: '160px', background: '#111118', borderRight: '1px solid rgba(255,255,255,0.07)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
          <div style={{ padding: '0.7rem 0.8rem', borderBottom: '1px solid rgba(255,255,255,0.06)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.1em', color: 'rgba(255,255,255,0.35)' }}>ELEMENTS</span>
            <button onClick={addElement} style={{ background: 'none', border: 'none', color: '#D4AF37', cursor: 'pointer', fontSize: '1rem', lineHeight: 1, padding: '0.1rem' }} title="Add element">+</button>
          </div>
          <div style={{ flex: 1, overflowY: 'auto' }}>
            {elements.map((el, i) => (
              <div key={el.id}
                onClick={() => setSelectedId(el.id)}
                style={{
                  padding: '0.6rem 0.8rem', cursor: 'pointer',
                  background: selectedId === el.id ? 'rgba(212,175,55,0.1)' : 'transparent',
                  borderLeft: `3px solid ${selectedId === el.id ? '#D4AF37' : 'transparent'}`,
                  display: 'flex', alignItems: 'center', gap: '0.5rem',
                  transition: 'all 0.13s',
                }}>
                <div style={{ width: '12px', height: '12px', borderRadius: el.shape === 'circle' || el.shape === 'ring' ? '50%' : '2px', background: el.shape === 'ring' ? 'transparent' : el.color, border: el.shape === 'ring' ? `2px solid ${el.color}` : 'none', flexShrink: 0 }} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontFamily: 'Georgia, serif', fontSize: '0.78rem', color: selectedId === el.id ? '#D4AF37' : '#F0EDE8', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{el.name}</div>
                  <div style={{ fontFamily: '"Courier New", monospace', fontSize: '0.58rem', color: 'rgba(255,255,255,0.28)' }}>{el.shape}</div>
                </div>
                {elements.length > 1 && (
                  <button onClick={e => { e.stopPropagation(); removeElement(el.id) }}
                    style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.2)', cursor: 'pointer', fontSize: '0.75rem', padding: 0, lineHeight: 1 }}
                    onMouseEnter={e => e.target.style.color = '#E05070'}
                    onMouseLeave={e => e.target.style.color = 'rgba(255,255,255,0.2)'}
                  >✕</button>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* ── Centre: Canvas ── */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
          <div style={{ flex: 1, position: 'relative', background: '#16161F', overflow: 'hidden' }}
            onClick={() => setSelectedId(null)}>

            {/* Grid */}
            <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', opacity: 0.06 }}>
              <defs>
                <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                  <path d="M 40 0 L 0 0 0 40" fill="none" stroke="white" strokeWidth="0.5" />
                </pattern>
              </defs>
              <rect width="100%" height="100%" fill="url(#grid)" />
            </svg>

            {/* Centre crosshair */}
            <div style={{ position: 'absolute', top: '50%', left: '50%', width: '1px', height: '40px', background: 'rgba(255,255,255,0.08)', transform: 'translateX(-50%) translateY(-50%)' }} />
            <div style={{ position: 'absolute', top: '50%', left: '50%', width: '40px', height: '1px', background: 'rgba(255,255,255,0.08)', transform: 'translateX(-50%) translateY(-50%)' }} />

            {/* Elements */}
            {elements.map(el => {
              const props = getPropsAtTime(el.keyframes, currentTime)
              return (
                <ShapeEl key={el.id} el={el} props={props}
                  selected={selectedId === el.id}
                  onClick={e => { e.stopPropagation(); setSelectedId(el.id) }}
                />
              )
            })}

            {/* Time indicator */}
            <div style={{ position: 'absolute', bottom: '8px', right: '12px', fontFamily: '"Courier New", monospace', fontSize: '0.65rem', color: 'rgba(255,255,255,0.25)' }}>
              {((currentTime / 100) * duration).toFixed(0)}ms / {duration}ms
            </div>
          </div>

          {/* ── Timeline ── */}
          <div style={{ height: TIMELINE_H, background: '#0F0F1A', borderTop: '1px solid rgba(255,255,255,0.08)', display: 'flex', flexDirection: 'column' }}>

            {/* Scrubber */}
            <div ref={timelineRef}
              style={{ height: '28px', position: 'relative', cursor: 'col-resize', background: 'rgba(0,0,0,0.3)', flexShrink: 0, borderBottom: '1px solid rgba(255,255,255,0.06)' }}
              onMouseDown={e => { setTimelineDragging(true); scrubTimeline(e) }}
              onMouseMove={e => { if (timelineDragging) scrubTimeline(e) }}
              onMouseUp={() => setTimelineDragging(false)}
              onMouseLeave={() => setTimelineDragging(false)}
            >
              {/* Tick marks */}
              {[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100].map(t => (
                <div key={t} style={{ position: 'absolute', left: `${t}%`, top: 0, bottom: 0, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                  <div style={{ width: '1px', height: t % 50 === 0 ? '10px' : '6px', background: 'rgba(255,255,255,0.15)', marginTop: t % 50 === 0 ? '4px' : '6px' }} />
                  {t % 25 === 0 && <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.5rem', color: 'rgba(255,255,255,0.25)', marginTop: '2px' }}>{((t / 100) * duration).toFixed(0)}</span>}
                </div>
              ))}

              {/* Playhead */}
              <div style={{ position: 'absolute', left: `${currentTime}%`, top: 0, bottom: 0, width: '2px', background: '#D4AF37', pointerEvents: 'none', boxShadow: '0 0 6px #D4AF37' }}>
                <div style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: 0, height: 0, borderLeft: '5px solid transparent', borderRight: '5px solid transparent', borderTop: '7px solid #D4AF37' }} />
              </div>
            </div>

            {/* Keyframe rows */}
            <div style={{ flex: 1, overflowY: 'auto' }}>
              {elements.map(el => (
                <div key={el.id} style={{ height: '32px', display: 'flex', alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.04)', position: 'relative' }}>
                  {/* Row label */}
                  <div style={{ width: '160px', flexShrink: 0, padding: '0 0.8rem', display: 'flex', alignItems: 'center', gap: '0.4rem', borderRight: '1px solid rgba(255,255,255,0.06)' }}>
                    <div style={{ width: '8px', height: '8px', borderRadius: el.shape === 'circle' ? '50%' : '2px', background: el.color, flexShrink: 0 }} />
                    <span style={{ fontFamily: '"Courier New", monospace', fontSize: '0.6rem', color: selectedId === el.id ? '#D4AF37' : 'rgba(255,255,255,0.4)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{el.name}</span>
                  </div>

                  {/* Keyframe track */}
                  <div style={{ flex: 1, position: 'relative', height: '100%', cursor: 'pointer' }}
                    onClick={e => {
                      if (!timelineRef.current) return
                      const rect = e.currentTarget.getBoundingClientRect()
                      const t = Math.round(((e.clientX - rect.left) / rect.width) * 100)
                      addOrUpdateKf(el.id, Math.max(0, Math.min(100, t)), {})
                      setSelectedId(el.id)
                      setCurrentTime(t)
                    }}>

                    {/* Track line */}
                    <div style={{ position: 'absolute', top: '50%', left: 0, right: 0, height: '2px', background: 'rgba(255,255,255,0.06)', transform: 'translateY(-50%)' }} />

                    {/* Keyframe diamonds */}
                    {el.keyframes.map((kf, ki) => (
                      <div key={ki}
                        style={{
                          position: 'absolute', left: `${kf.time}%`, top: '50%',
                          width: '10px', height: '10px',
                          background: selectedId === el.id ? '#D4AF37' : el.color,
                          transform: 'translate(-50%, -50%) rotate(45deg)',
                          cursor: 'pointer',
                          boxShadow: selectedId === el.id ? `0 0 6px #D4AF37` : 'none',
                          zIndex: 2,
                          transition: 'background 0.13s',
                        }}
                        onClick={e => {
                          e.stopPropagation()
                          setCurrentTime(kf.time)
                          setSelectedId(el.id)
                          pauseTimeRef.current = kf.time
                        }}
                        onContextMenu={e => { e.preventDefault(); removeKf(el.id, ki) }}
                        title={`${kf.time}% — right-click to delete`}
                      />
                    ))}
                  </div>
                </div>
              ))}
              {elements.length === 0 && (
                <div style={{ padding: '1rem', textAlign: 'center', fontFamily: '"Courier New", monospace', fontSize: '0.65rem', color: 'rgba(255,255,255,0.2)' }}>add elements to see their tracks</div>
              )}
            </div>

            {/* Timeline hint */}
            <div style={{ padding: '0.2rem 0.8rem', borderTop: '1px solid rgba(255,255,255,0.04)', display: 'flex', gap: '1.5rem' }}>
              {[['click track', 'add keyframe'], ['right-click ◆', 'delete keyframe'], ['drag top bar', 'scrub time']].map(([k, v]) => (
                <span key={k} style={{ fontFamily: '"Courier New", monospace', fontSize: '0.52rem', color: 'rgba(255,255,255,0.18)' }}>
                  <span style={{ color: 'rgba(212,175,55,0.5)' }}>{k}</span> → {v}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* ── Right: Properties panel ── */}
        <div style={{ width: PANEL_W, background: '#111118', borderLeft: '1px solid rgba(255,255,255,0.07)', overflowY: 'auto', flexShrink: 0 }}>
          {!selected ? (
            <div style={{ padding: '2rem 1rem', textAlign: 'center', fontFamily: 'Georgia, serif', fontSize: '0.8rem', color: 'rgba(255,255,255,0.2)' }}>
              select an element to edit its properties
            </div>
          ) : (
            <>
              {/* Element meta */}
              <div style={{ padding: '0.7rem 0.8rem', borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                <input value={selected.name} onChange={e => updateElement(selected.id, { name: e.target.value })}
                  style={{ width: '100%', background: 'transparent', border: 'none', outline: 'none', fontFamily: 'Georgia, serif', fontSize: '0.9rem', fontWeight: 700, color: '#D4AF37', boxSizing: 'border-box' }}
                />
                <div style={{ fontFamily: '"Courier New", monospace', fontSize: '0.58rem', color: 'rgba(255,255,255,0.25)', marginTop: '0.1rem' }}>
                  {selected.keyframes.length} keyframe{selected.keyframes.length !== 1 ? 's' : ''} · t={currentTime.toFixed(1)}%
                </div>
              </div>

              <PanelSection title="SHAPE">
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.3rem', marginBottom: '0.7rem' }}>
                  {SHAPES.map(s => (
                    <button key={s} onClick={() => updateElement(selected.id, { shape: s })}
                      style={{
                        padding: '0.35rem', borderRadius: '5px', cursor: 'pointer',
                        background: selected.shape === s ? 'rgba(212,175,55,0.2)' : 'rgba(255,255,255,0.04)',
                        border: `1px solid ${selected.shape === s ? '#D4AF37' : 'rgba(255,255,255,0.08)'}`,
                        color: selected.shape === s ? '#D4AF37' : 'rgba(255,255,255,0.4)',
                        fontFamily: '"Courier New", monospace', fontSize: '0.58rem',
                        transition: 'all 0.13s',
                      }}
                    >{s}</button>
                  ))}
                </div>
                <Slider label="SIZE" value={selected.size} min={20} max={160} step={2} onChange={v => updateElement(selected.id, { size: v })} unit="px" />
              </PanelSection>

              <PanelSection title="COLOUR">
                <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap', marginBottom: '0.5rem' }}>
                  {ELEMENT_COLORS.map(c => (
                    <button key={c} onClick={() => handlePropChange('color', c)}
                      style={{ width: '22px', height: '22px', borderRadius: '50%', background: c, border: `2px solid ${currentProps.color === c ? '#fff' : 'transparent'}`, cursor: 'pointer', transition: 'border 0.1s' }}
                    />
                  ))}
                </div>
                <input type="color" value={currentProps.color}
                  onChange={e => handlePropChange('color', e.target.value)}
                  style={{ width: '100%', height: '28px', borderRadius: '5px', border: '1px solid rgba(255,255,255,0.1)', background: 'none', cursor: 'pointer' }}
                />
              </PanelSection>

              <PanelSection title="TRANSFORM">
                <Slider label="X" value={currentProps.x} min={-300} max={300} step={1} onChange={v => handlePropChange('x', v)} unit="px" />
                <Slider label="Y" value={currentProps.y} min={-300} max={300} step={1} onChange={v => handlePropChange('y', v)} unit="px" />
                <Slider label="ROTATE" value={currentProps.rotate} min={-360} max={360} step={1} onChange={v => handlePropChange('rotate', v)} unit="°" />
                <Slider label="SCALE X" value={currentProps.scaleX} min={0} max={3} step={0.01} onChange={v => handlePropChange('scaleX', v)} />
                <Slider label="SCALE Y" value={currentProps.scaleY} min={0} max={3} step={0.01} onChange={v => handlePropChange('scaleY', v)} />
              </PanelSection>

              <PanelSection title="OPACITY">
                <Slider label="OPACITY" value={currentProps.opacity} min={0} max={1} step={0.01} onChange={v => handlePropChange('opacity', v)} />
              </PanelSection>

              {/* Add keyframe button */}
              <div style={{ padding: '0.8rem' }}>
                <button
                  onClick={() => addOrUpdateKf(selected.id, Math.round(currentTime), {})}
                  style={{
                    width: '100%', padding: '0.55rem',
                    background: 'rgba(212,175,55,0.12)', border: '2px solid rgba(212,175,55,0.3)',
                    borderRadius: '7px', color: '#D4AF37',
                    fontFamily: 'Georgia, serif', fontSize: '0.8rem', fontWeight: 700,
                    cursor: 'pointer', transition: 'all 0.13s',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.background = 'rgba(212,175,55,0.22)' }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'rgba(212,175,55,0.12)' }}
                >
                  ◆ set keyframe at {currentTime.toFixed(0)}%
                </button>
              </div>
            </>
          )}
        </div>
      </div>

      {/* ── CSS Export panel ── */}
      {showCode && (
        <div style={{
          position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', zIndex: 100,
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2rem',
        }} onClick={() => setShowCode(false)}>
          <div onClick={e => e.stopPropagation()} style={{
            background: '#111118', border: '2px solid rgba(212,175,55,0.3)',
            borderRadius: '16px', width: '100%', maxWidth: '680px', maxHeight: '80vh',
            display: 'flex', flexDirection: 'column', overflow: 'hidden',
          }}>
            <div style={{ padding: '1rem 1.2rem', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <div style={{ fontFamily: 'Georgia, serif', fontSize: '1rem', fontWeight: 700, color: '#F0EDE8' }}>CSS Export</div>
                <div style={{ fontFamily: '"Courier New", monospace', fontSize: '0.62rem', color: 'rgba(255,255,255,0.3)', marginTop: '0.1rem' }}>{elements.length} element{elements.length !== 1 ? 's' : ''} · {easing} · {duration}ms</div>
              </div>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button onClick={copyCSS} style={{ padding: '0.45rem 1rem', background: copied ? 'rgba(78,205,196,0.2)' : 'rgba(212,175,55,0.15)', border: `2px solid ${copied ? '#4ECDC4' : '#D4AF37'}`, borderRadius: '7px', color: copied ? '#4ECDC4' : '#D4AF37', fontFamily: 'Georgia, serif', fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer' }}>
                  {copied ? '✓ copied!' : '⎘ copy'}
                </button>
                <button onClick={() => setShowCode(false)} style={{ padding: '0.45rem 0.7rem', background: 'transparent', border: '2px solid rgba(255,255,255,0.12)', borderRadius: '7px', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '0.9rem' }}>✕</button>
              </div>
            </div>
            <pre style={{
              flex: 1, overflowY: 'auto', margin: 0, padding: '1.2rem',
              fontFamily: '"Courier New", monospace', fontSize: '0.75rem',
              color: '#A8D8A8', lineHeight: 1.7,
              background: '#0A0A10',
              scrollbarWidth: 'thin', scrollbarColor: 'rgba(212,175,55,0.3) transparent',
            }}>
              {cssCode}
            </pre>
          </div>
        </div>
      )}

      <style>{`
        input[type=range] { -webkit-appearance: none; height: 4px; border-radius: 2px; background: rgba(255,255,255,0.1); }
        input[type=range]::-webkit-slider-thumb { -webkit-appearance: none; width: 14px; height: 14px; border-radius: 50%; background: #D4AF37; cursor: pointer; box-shadow: 0 0 6px rgba(212,175,55,0.5); }
        input[type=range]::-moz-range-thumb { width: 14px; height: 14px; border-radius: 50%; background: #D4AF37; cursor: pointer; border: none; }
        ::-webkit-scrollbar { width: 4px; height: 4px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(212,175,55,0.25); border-radius: 2px; }
      `}</style>
    </div>
  )
}